[2022-05-02 16:54:42,402] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: podsight_ETL.extract_podsight_data manual__2022-05-02T16:37:08.025311+00:00 [queued]>
[2022-05-02 16:54:42,416] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: podsight_ETL.extract_podsight_data manual__2022-05-02T16:37:08.025311+00:00 [queued]>
[2022-05-02 16:54:42,418] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:54:42,421] {taskinstance.py:1250} INFO - Starting attempt 10 of 13
[2022-05-02 16:54:42,423] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:54:42,446] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): extract_podsight_data> on 2022-05-02 16:37:08.025311+00:00
[2022-05-02 16:54:42,451] {standard_task_runner.py:52} INFO - Started process 483 to run task
[2022-05-02 16:54:42,456] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'podsight_ETL', 'extract_podsight_data', 'manual__2022-05-02T16:37:08.025311+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/podsight_ETL.py', '--cfg-path', '/tmp/tmp3ab38gtm', '--error-file', '/tmp/tmp2c3pgckr']
[2022-05-02 16:54:42,457] {standard_task_runner.py:80} INFO - Job 107: Subtask extract_podsight_data
[2022-05-02 16:54:42,516] {logging_mixin.py:109} INFO - Running <TaskInstance: podsight_ETL.extract_podsight_data manual__2022-05-02T16:37:08.025311+00:00 [running]> on host 4c9d01f48299
[2022-05-02 16:54:42,566] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=hamza.ahmed@liquidagency.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=podsight_ETL
AIRFLOW_CTX_TASK_ID=extract_podsight_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-02T16:37:08.025311+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-02T16:37:08.025311+00:00
[2022-05-02 16:54:42,568] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-02 16:54:42,569] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/hamza.ahmed/Coding Projects/Python_Apps/Docker_Applications/Airflow_Docker_Apps/Python_Scripts/podsight_API_JumpCloud.py']
[2022-05-02 16:54:42,581] {subprocess.py:85} INFO - Output:
[2022-05-02 16:54:42,583] {subprocess.py:89} INFO - bash: /Users/hamza.ahmed/Coding: No such file or directory
[2022-05-02 16:54:42,584] {subprocess.py:93} INFO - Command exited with return code 127
[2022-05-02 16:54:42,598] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-05-02 16:54:42,605] {taskinstance.py:1288} INFO - Marking task as UP_FOR_RETRY. dag_id=podsight_ETL, task_id=extract_podsight_data, execution_date=20220502T163708, start_date=20220502T165442, end_date=20220502T165442
[2022-05-02 16:54:42,619] {standard_task_runner.py:98} ERROR - Failed to execute job 107 for task extract_podsight_data (Bash command failed. The command returned a non-zero exit code 127.; 483)
[2022-05-02 16:54:42,631] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-02 16:54:42,672] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
