[2022-05-02 17:04:25,319] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: podsight_ETL.extract_podsight_data manual__2022-05-02T17:01:21.799626+00:00 [queued]>
[2022-05-02 17:04:25,331] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: podsight_ETL.extract_podsight_data manual__2022-05-02T17:01:21.799626+00:00 [queued]>
[2022-05-02 17:04:25,332] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 17:04:25,332] {taskinstance.py:1250} INFO - Starting attempt 4 of 6
[2022-05-02 17:04:25,333] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 17:04:25,347] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): extract_podsight_data> on 2022-05-02 17:01:21.799626+00:00
[2022-05-02 17:04:25,353] {standard_task_runner.py:52} INFO - Started process 970 to run task
[2022-05-02 17:04:25,357] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'podsight_ETL', 'extract_podsight_data', 'manual__2022-05-02T17:01:21.799626+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/podsight_ETL.py', '--cfg-path', '/tmp/tmp1w225ghd', '--error-file', '/tmp/tmpxc7b_vr5']
[2022-05-02 17:04:25,358] {standard_task_runner.py:80} INFO - Job 118: Subtask extract_podsight_data
[2022-05-02 17:04:25,415] {logging_mixin.py:109} INFO - Running <TaskInstance: podsight_ETL.extract_podsight_data manual__2022-05-02T17:01:21.799626+00:00 [running]> on host 4c9d01f48299
[2022-05-02 17:04:25,465] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=hamza.ahmed@liquidagency.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=podsight_ETL
AIRFLOW_CTX_TASK_ID=extract_podsight_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-02T17:01:21.799626+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-02T17:01:21.799626+00:00
[2022-05-02 17:04:25,467] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-02 17:04:25,468] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/hamza.ahmed/Coding Projects/Python_Apps/Docker_Applications/Airflow_Docker_Apps/Python_Scripts/podsight_API_JumpCloud.py']
[2022-05-02 17:04:25,480] {subprocess.py:85} INFO - Output:
[2022-05-02 17:04:25,482] {subprocess.py:89} INFO - bash: /Users/hamza.ahmed/Coding: No such file or directory
[2022-05-02 17:04:25,484] {subprocess.py:93} INFO - Command exited with return code 127
[2022-05-02 17:04:25,497] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-05-02 17:04:25,505] {taskinstance.py:1288} INFO - Marking task as UP_FOR_RETRY. dag_id=podsight_ETL, task_id=extract_podsight_data, execution_date=20220502T170121, start_date=20220502T170425, end_date=20220502T170425
[2022-05-02 17:04:25,518] {standard_task_runner.py:98} ERROR - Failed to execute job 118 for task extract_podsight_data (Bash command failed. The command returned a non-zero exit code 127.; 970)
[2022-05-02 17:04:25,530] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-02 17:04:25,570] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
